CREATE DATABASE [QL_DVGiaiTri]
USE [QL_DVGiaiTri]

CREATE TABLE [dbo].[Video](
	[IDVd] [nvarchar](50) NOT NULL,
	[Titile] [nvarchar](255) NOT NULL,
	[Poster] [bit] NOT NULL,
	[Views] [int] NOT NULL,
	[Description] [varchar](255) NOT NULL,
	[Active] [bit] NOT NULL
 CONSTRAINT [PK_Video] PRIMARY KEY CLUSTERED 
(
	[IDVd] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Favorite](
	[IDFv] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](50) NOT NULL,
	[VideoId] [nvarchar](50) NOT NULL,
	[LikeDate] [date] NOT NULL
 CONSTRAINT [PK_Favorite] PRIMARY KEY CLUSTERED 
(
	[IDFv] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[Share](
	[IDS] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](50) NOT NULL,
	[VideoId] [nvarchar](50) NOT NULL,
	[Email] [varchar](50) NULL,
	[ShareDate] [date] NOT NULL
 CONSTRAINT [PK_Share] PRIMARY KEY CLUSTERED 
(
	[IDS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[User](
	[IDUs] [varchar](50) NOT NULL,
	[Fullname] [nvarchar](50) NULL,
	[MatKhau] [nvarchar](50) NULL,
	[Email] [nvarchar](50) NULL,
	[Admin] [bit] NULL
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[IDUs] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Favorite]  WITH CHECK ADD  CONSTRAINT [FK_favorite_Video] FOREIGN KEY([UserId])
REFERENCES [dbo].[Video] ([IDVd])
GO
ALTER TABLE [dbo].[Favorite] CHECK CONSTRAINT [FK_favorite_Video]

ALTER TABLE [dbo].[Favorite]  WITH CHECK ADD  CONSTRAINT [FK_favorite_Video1] FOREIGN KEY([VideoId])
REFERENCES [dbo].[Video] ([IDVd])
GO
ALTER TABLE [dbo].[Favorite] CHECK CONSTRAINT [FK_favorite_Video1]

